A = int(input("Введіть довжини першого відрізку: "))
B = int(input("Введіть довжини другого відрізку: "))
C = int(input("Введіть довжини третього відрізку: "))
D = int(input("Введіть довжини четвертого відрізку: "))
E = int(input("Введіть довжини п'ятого відрізку: "))
v=(('AB', A), ('BC', B), ('CD', C), ('DE', D), ('EF', E))
slovnik=dict(v)
print("Словник: ", slovnik)
print("Кількість сторін: ",len(slovnik))
print("Довжина найбільшої сторони багатокутника: ",max(slovnik.values()))
print("Довжина всіх сторін багатокутника: ",sum(slovnik.values()))
del(slovnik['BC'])
print("Словник без 'BC': ",slovnik)
